resources:
- name: booklit
  type: git
  source: {uri: "https://github.com/lampalork85/concourse-tuto"}

jobs:
- name: unit
  plan:
  - get: booklit
    trigger: true
  - task: test
    input_mapping:
      booklit: booklit
    file: booklit/ci/test.yml
- name: unit2
  plan:
  - get: booklit
    passed: [unit]
    #trigger: true
  - task: test
    input_mapping:
      booklit: booklit
    file: booklit/ci/test.yml
- name: unit3
  plan:
  - get: booklit
    passed: [unit2]
    #trigger: true
  - task: test
    input_mapping:
      booklit: booklit
    file: booklit/ci/test.yml
